name: Build site on main branch update

on:
  push:
    branches:
      - main

jobs:
  build-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@^6
      - uses: actions/cache@v2
        id: pnpm-cache # use this to check for `cache-hit` (`steps.pnpm-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Deploy to GitHub Pages
        run: |
          git config user.name 'Tom Chen'
          git config user.email 'developer@tomchentw.com'
          git add -f out
          git stash
          git switch gh-pages
          git rm -rf .
          git clean -fd
          git stash pop
          git mv out/* .
          git fetch --all
          git restore --source=origin/main .github
          git restore --source=origin/gh-pages data
          git add -A
          git commit -m "deploy: $GITHUB_SHA"
          git push
