name: Run crawl script

on:
  workflow_dispatch: # Trigger this inifinite loop MANUALLY!!!
  push:
    branches:
      - gh-pages

jobs:
  run-crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@^6
      - uses: actions/cache@v2
        id: pnpm-cache # use this to check for `cache-hit` (`steps.pnpm-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - run: pnpm install --frozen-lockfile
      - run: pnpm cron crawl
      - name: Update data/raw
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} # Trigger run-crawl.yml
          publish_dir: ./public/data/raw
          destination_dir: ./data/raw
